---
- name: testing tags
  hosts: localhost
  tasks:
    - name: T1
      debug:
        msg: Task 1
      tags:
        - devel
        - testing

    - name: T2
      debug:
        msg: Task 2
      tags:
        - prod
        - testing

    - name: T3
      debug:
        msg: Task 3

    - name: T4
      debug:
        msg: Always
      tags:
        - always